import type { ToolMeta, ToolCategory } from '@pdf-saas/shared'
import type { ToolIconName } from './icon-map'

export interface ToolDefinition extends ToolMeta {
  icon: ToolIconName
}

const def = (
  slug: string,
  name: string,
  shortName: string,
  category: ToolCategory,
  description: string,
  icon: ToolDefinition['icon'],
  keywords: string[],
): ToolDefinition => ({ slug, name, shortName, category, description, icon, keywords })

export const toolDefinitions: ToolDefinition[] = [
  def(
    'pdf-splitter',
    'Split PDF',
    'Split',
    'PDF',
    'Pick the exact pages you want and download them as a brand-new PDF.',
    'file-split',
    ['split pdf', 'extract pages pdf', 'remove pages pdf', 'pdf page splitter'],
  ),
  def(
    'pdf-merger',
    'Merge PDFs',
    'Merge',
    'PDF',
    'Combine multiple PDF files into a single document in the order you choose.',
    'file-merge',
    ['merge pdf', 'combine pdf', 'join pdf files', 'pdf merger'],
  ),
  def(
    'pdf-delete-pages',
    'Delete PDF Pages',
    'Delete',
    'PDF',
    'Remove unwanted pages from a PDF with a visual thumbnail picker.',
    'trash',
    ['delete pages pdf', 'remove pages from pdf', 'pdf page deleter'],
  ),
  def(
    'pdf-extractor',
    'Extract PDF Pages',
    'Extract',
    'PDF',
    'Pull out specific pages using simple ranges like 2, 5, 7-10.',
    'scissors',
    ['extract pages pdf', 'pdf page extractor', 'save selected pages pdf'],
  ),
  def(
    'pdf-rotator',
    'Rotate PDF',
    'Rotate',
    'PDF',
    'Rotate pages 90, 180 or 270 degrees — one page or the whole document.',
    'rotate',
    ['rotate pdf', 'rotate pages pdf', 'pdf rotate 90 degrees'],
  ),
  def(
    'jpg-to-pdf',
    'JPG to PDF',
    'JPG→PDF',
    'PDF',
    'Turn images (JPG, PNG, WEBP) into a single PDF, reorder before exporting.',
    'image-to-pdf',
    ['jpg to pdf', 'image to pdf', 'png to pdf', 'create pdf from images'],
  ),
  def(
    'pdf-to-jpg',
    'PDF to JPG',
    'PDF→JPG',
    'PDF',
    'Export PDF pages as high-quality JPG images.',
    'pdf-to-image',
    ['pdf to jpg', 'pdf to image', 'convert pdf pages to images'],
  ),
  def(
    'pdf-compressor',
    'Compress PDF',
    'Compress',
    'PDF',
    'Shrink PDF file size with balanced, strong or maximum compression.',
    'archive',
    ['compress pdf', 'reduce pdf size', 'smaller pdf', 'pdf compressor'],
  ),
  def(
    'pdf-protector',
    'Protect PDF',
    'Protect',
    'PDF',
    'Lock a PDF with a password so only people you choose can open it.',
    'lock',
    ['protect pdf', 'password protect pdf', 'lock pdf', 'encrypt pdf'],
  ),
  def(
    'pdf-unlocker',
    'Unlock PDF',
    'Unlock',
    'PDF',
    'Remove a password from a PDF and download an open copy.',
    'unlock',
    ['unlock pdf', 'remove pdf password', 'decrypt pdf', 'unprotect pdf'],
  ),
  def(
    'pdf-watermark',
    'Add Watermark',
    'Watermark',
    'PDF',
    'Stamp text across every page — perfect for marking drafts or confidential files.',
    'stamp',
    ['pdf watermark', 'add watermark to pdf', 'stamp pdf', 'confidential pdf'],
  ),
  def(
    'pdf-page-numbers',
    'Page Numbers',
    'Number',
    'PDF',
    'Add page numbers to a PDF in the position and format you prefer.',
    'list-ordered',
    ['pdf page numbers', 'number pages pdf', 'add page numbers to pdf'],
  ),
  def(
    'pdf-cropper',
    'Crop PDF',
    'Crop',
    'PDF',
    'Trim the edges of every page by percentage to remove unwanted margins.',
    'frame',
    ['crop pdf', 'trim pdf margins', 'remove pdf borders', 'pdf crop pages'],
  ),
  def(
    'pdf-organizer',
    'Organize Pages',
    'Organize',
    'PDF',
    'Reorder pages however you like with a simple list like 3, 1, 4, 2.',
    'shuffle',
    ['reorder pdf pages', 'organize pdf', 'change pdf page order', 'sort pdf pages'],
  ),
  def(
    'image-compressor',
    'Image Compressor',
    'Compress',
    'Image',
    'Reduce the file size of JPG, PNG and WEBP images with quality control.',
    'image-compress',
    ['compress image', 'reduce image size', 'image file size', 'optimize image'],
  ),
  def(
    'image-resizer',
    'Image Resizer',
    'Resize',
    'Image',
    'Resize images to exact dimensions while keeping quality and aspect ratio.',
    'ruler',
    ['resize image', 'image dimensions', 'resize photo', 'scale image'],
  ),
  def(
    'image-cropper',
    'Image Cropper',
    'Crop',
    'Image',
    'Crop images visually with a draggable selection rectangle.',
    'crop',
    ['crop image', 'crop photo', 'crop picture', 'image crop tool'],
  ),
  def(
    'image-converter',
    'Image Converter',
    'Convert',
    'Image',
    'Convert between JPG, PNG and WEBP formats with batch support.',
    'refresh',
    ['convert image', 'jpg to png', 'png to jpg', 'webp converter'],
  ),
  def(
    'image-text',
    'Add Text to Image',
    'Add Text',
    'Image',
    'Overlay a caption on your image with custom text, color, size and position.',
    'type',
    ['add text to image', 'caption image', 'text overlay', 'watermark image text'],
  ),
  def(
    'image-passport',
    'Passport Photo',
    'Passport',
    'Image',
    'Create passport-sized photos with configurable dimensions, background color, and face cropping.',
    'passport',
    ['passport photo', 'id photo', 'visa photo', 'passport size photo'],
  ),
  def(
    'image-circle',
    'Circle Image',
    'Circle',
    'Image',
    'Crop any image into a perfect circle with transparent PNG output and optional background/border.',
    'circle',
    ['circle image', 'circular crop', 'round image', 'circle crop'],
  ),
  def(
    'image-background remover',
    'Remove Background',
    'Remove BG',
    'Image',
    'Remove image backgrounds locally using color-based detection. No data leaves your browser.',
    'eraser',
    ['remove background', 'bg remover', 'transparent background', 'cut out image'],
  ),
  def(
    'image-quality',
    'Image Quality Analyzer',
    'Analyze',
    'Image',
    'Analyze image resolution, format, estimated quality, complexity, and get tool recommendations.',
    'scan-search',
    ['image quality', 'image analysis', 'check image quality', 'image info'],
  ),
  def(
    'image-resize-purpose',
    'Resize for Purpose',
    'Resize+',
    'Image',
    'Resize images for specific platforms: Instagram, Facebook, Twitter, email, web, and more.',
    'maximize',
    ['resize for social media', 'resize for instagram', 'resize for web', 'social media image size'],
  ),
  def(
    'pdf-to-word',
    'PDF to Word',
    'PDF→Word',
    'Office',
    'Convert PDF text into an editable Word document you can open in Word or Google Docs.',
    'file-text',
    ['pdf to word', 'convert pdf to docx', 'pdf to editable document'],
  ),
  def(
    'pdf-to-excel',
    'PDF to Excel',
    'PDF→Excel',
    'Office',
    'Turn PDF text into an Excel spreadsheet, one row per line.',
    'file-spreadsheet',
    ['pdf to excel', 'convert pdf to xlsx', 'pdf to spreadsheet'],
  ),
  def(
    'pdf-to-powerpoint',
    'PDF to PowerPoint',
    'PDF→PPT',
    'Office',
    'Turn each PDF page into a PowerPoint slide, ready to present.',
    'presentation',
    ['pdf to powerpoint', 'pdf to pptx', 'convert pdf to ppt'],
  ),
  def(
    'word-to-pdf',
    'Word to PDF',
    'Word→PDF',
    'Office',
    'Convert Word documents into a clean PDF.',
    'file-output',
    ['word to pdf', 'docx to pdf', 'convert word document to pdf'],
  ),
]

export const pdfTools = toolDefinitions.filter((t) => t.category === 'PDF')
export const imageTools = toolDefinitions.filter((t) => t.category === 'Image')
export const officeTools = toolDefinitions.filter((t) => t.category === 'Office')

export function getTool(slug: string): ToolDefinition | undefined {
  return toolDefinitions.find((t) => t.slug === slug)
}
